"""Extract ASCII bitmap glyphs from PebbleOS Gothic PBF fonts.

Usage: python scripts/generate-preview-fonts.py /path/to/pbf-files
Source: https://github.com/coredevices/PebbleOS/tree/main/resources
GOTHIC_14, GOTHIC_18_BOLD and GOTHIC_24 are in common/base/pbf;
the other variants are in normal/base/pbf. No font substitution or scaling.
"""
import json
from pathlib import Path
import struct
import sys

fonts = {}
for size in (14, 18, 24, 28):
    for bold in (False, True):
        data = (Path(sys.argv[1]) / ('GOTHIC_' + str(size) + ('_BOLD' if bold else '') + '.pbf')).read_bytes()
        version, height, count, wildcard, buckets, cp_bytes, header_size, features = struct.unpack_from('<BBHHBBBB', data)
        assert version == 3 and features == 1 and cp_bytes == 2, 'Expected uncompressed v3 font with 16-bit offsets'
        offsets = header_size + buckets * 4
        bitmaps = offsets + count * 4
        glyphs = {}
        for i in range(count):
            code, offset = struct.unpack_from('<HH', data, offsets + i * 4)
            if not 32 <= code <= 126:
                continue
            start = bitmaps + offset
            w, h, left, top, advance = struct.unpack_from('<BBbbb', data, start)
            pixels = data[start + 5:start + 5 + (w * h + 7) // 8]
            rows = [sum(((pixels[(y * w + x) // 8] >> ((y * w + x) % 8)) & 1) << x for x in range(w)) for y in range(h)]
            glyphs[chr(code)] = [w, h, left, top, advance, rows]
        assert len(glyphs) == 95
        fonts[str(size) + ('b' if bold else 'r')] = {'height': height, 'glyphs': glyphs}
Path('src/config/preview-fonts.js').write_text('// Generated by scripts/generate-preview-fonts.py from PebbleOS system fonts.\nwindow.BibblePreviewFonts = ' + json.dumps(fonts, separators=(',', ':')) + ';\n')
